
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-scm-dippynark-co-uk-v1alpha1-githubwebhook
  failurePolicy: Fail
  name: mgithubwebhook.kb.io
  rules:
  - apiGroups:
    - scm.dippynark.co.uk
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubwebhooks
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-scm-dippynark-co-uk-v1alpha1-githubwebhook
  failurePolicy: Fail
  name: vgithubwebhook.kb.io
  rules:
  - apiGroups:
    - scm.dippynark.co.uk
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - githubwebhooks
  sideEffects: None
