apiVersion: scm.dippynark.co.uk/v1alpha1
kind: GitHubWebhook
metadata:
  name: githubwebhook-sample
spec:
  repository:
    owner: dippynark
    name: kfmt
  payloadURL: https://test2.lukeaddison.co.uk
  contentType: application/json
  secret:
    name: github
    key: token
  insecureSSL: false
  events:
  - "*"
  active: true
